package edu.vassar.cs.cmpu331.errors;

import edu.vassar.cs.cmpu331.lex.TokenType;

/**
 * Base class for errors generated by the parts of the compiler.
 */
public abstract class CompilerError extends Exception
{
   
   /** The type of error.  New types should be added to the enumeration
    * as the compiler generates new errors.
    */
   public enum Type {BAD_COMMENT, ILLEGAL_CHARACTER, UNTERMINATED_COMMENT, IDENTIFIER_TOO_LONG, 
	   CONSTANT_TOO_LONG, BUFFER_OVERFLOW, BAD_TOKEN, MULTI_DECL, UN_DECL, ILLEGAL_FUNCTION,
	   ILLEGAL_TYPES, ILLEGAL_ETYPES, INVALID_SUBSCRIPT, MISPLACED_SUBSCRIPT, INVALID_PROC,
	   TOO_MANY_PARMS, BAD_PARM_TYPE, BAD_ARRAY_BOUNDS, WRONG_NUM_PARMS, BAD_MOD_OPERANDS,
	   BAD_RELOP, RESERVED_NAME};

   /** The type of error represented by this object.  This field is declared
    * as final and must be set in the constructor.
    */
   protected final Type errorType;

   public CompilerError(Type errorType)
   {
      super("Unknown error");
      this.errorType = errorType;
   }

   public CompilerError(Type errorType, String message)
   {
      super(message);
      this.errorType = errorType;
   }
   
   public CompilerError(Type errorType, String message, TokenType t)
   {
      super(message);
      this.errorType = errorType;
   }

}

